apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-capa-argocd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JPedro2/capi-quickstart.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=false

    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
